 @include('header')

 <!-- Documentation page -->
<div class="min-h-[60vh]">
    <div class="w-11/12 justify-center text-left m-auto">
        <h1 class="text-5xl subpixel-antialiased font-semibold  m-auto text-red-700">Documentation</h1>
    </div>
    <div class="w-11/12 mx-auto " >
    	<h2 class="text-2xl text-red-700 font-semibold m-3">Usage</h2>
    	<div class="m-5">
    		<p>This Application is using MYSQL</p>
	    	<p>You could access the database through mysql workbrench to localhost by using username: sail, password: password</p>
	    	<p>If you have already installed Mysql Server on your local, please stop the service and make sure no one is using port 3306. It come with a MySQL server which powered by Docker.</p>
	    	<p>Config file ".env" is located at root dir</p>

	    	<ul class="list-decimal m-3">
	    		<li>Register a new account through the top-right "sign up" button</li>
	    		<li>Upload your Dataset by click the "Add a new file" button. (Only support CSV file, the first row much be column name)</li>
	    		<li>Once the file submitted. In Dashboard, click on the green "Convert To Table" button to create a new schema on the server. Select 'Disabled' option for column you dont want to import. (Make sure you double check the datatype, especially for datetime, select UNIXTimestamp  if the column is using timestamp</li>
	    		<li>Once the schema created, click the "My Tables" tab. Here will display the table you already have</li>
	    		<li>Click on "Generate Graph" button to create the Chart.</li>
	    		<li>Select the type of chart you would like to generate. Click 'Next step'</li>
	    		<li>Give the Chart a name in the name field. for Line, Bar, Radar Chart select the column you would like to place on the X axis. Y axis indicates the column you would like to use for second group by condition.</li>
				<li>By now, the chart has been created. Back to the Dashboard and select the "My Graphs" tab. it will display all charts you have created.</li>
				<li>You could click on the "View Chart" button to display the chart or copy and share the link in the last textField to share with others. People can visit this chart by using this link without authentication.</li>	    		
	    	</ul>
	    	
    	</div>

    	<h2 class="text-2xl text-red-700 font-semibold m-3">Important Files</h2>
    	<div class="m-5">
    		<ul class="list-disc m-3">
	    		<li>./.env server configration</li>
				<li>./tailwind.config.js  tailwind Config file</li>
				<li>./package-lock.json packages</li>
				<li>./docker-compose.yml docker env config file</li>
				<li>./Resources/views/* Files for the View (ending with .blade.php)</li>
				<li>./app/Http/Controllers/* Files for the controllers</li>
				<li>./app/Http/Models/* Files for the models for database</li>
				<li>./database/migrations/* Files for database structure</li>
				<li>./routes/api.php Routes for the RESTAPI</li>
				<li>./routes/web.php Routes for the website, used to switch between views</li>
	    	</ul>

    	</div>

    	<h2 class="text-2xl text-red-700 font-semibold m-3">REST API</h2>
    	<p class="text-gray-600 mx-5">This REST API allow externel user to access our database. (but read only)</p>
    	<p class="text-gray-600 mx-5">The URI below are dynamic generated, you could use it directly.</p>
    	<p class="text-gray-600 mx-5">{id} indicates the variable can be passed. http://host/api/files/{id} => http://host/api/files/1</p>
    	<h3 class="text-xl text-red-700 m-5">URI Structure</h3>

    	<p class="text-gray-600 mx-5 font-semibold">http://host/api/...</p>

    	<h3 class="text-xl text-red-700 m-5">Available Routes</h3>
    	<div class="m-5">
    		<p class="text-gray-600 font-semibold">{{url('/api/files');}}</p>
    		<p class="text-gray-600 m-1">Returns all uploaded files that recorded on the server</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/files/{id}');}}</p>
    		<p class="text-gray-600 m-1">Return the requested file by given file ID</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/tables');}}</p>
    		<p class="text-gray-600 m-1">Returns all uploaded tables that generated by users</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/tables/{id}');}}</p>
    		<p class="text-gray-600 m-1">Return the requested table by given table ID</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/tables/name/{name}');}}</p>
    		<p class="text-gray-600 m-1">Return the requested table by given table Name</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/tables/charts');}}</p>
    		<p class="text-gray-600 m-1">Return all generated charts avalible on the server</p>
	    	<p class="text-gray-600 font-semibold">{{url('/api/tables/charts/{id}');}}</p>
    		<p class="text-gray-600 m-1">Return the requested chart by given chart id</p>
    	</div>
    	
    </div>
</div>
@include('footer')